config/routes.rb
Rails.application.routes.draw do
  root "wing_orders#index"
  resources :wing_orders, only: [:index, :new, :create]
end

app/models/flavor.rb
class Flavor < ActiveRecord::Base
  has_many :order_flavors
  has_many :wing_orders, through: :order_flavors

  validates :name, presence: true
end

app/models/order_flavor.rb
class OrderFlavor < ActiveRecord::Base
  belongs_to :wing_order
  belongs_to :flavor

  validates :wing_order, presence: true
  validates :flavor, presence: true
end

app/models/wing_order.rb
class WingOrder < ActiveRecord::Base
  STATES = [
    ["Massachusetts", "MA"],
    ["New Hampshire", "NH"],
    ["Connecticut", "CT"],
    ["Maine", "ME"]
  ]

  QUANTITIES = [
    [10, "10 wings"],
    [25, "25 wings"],
    [50, "50 wings"],
    [100, "100 wings"]
  ]

  has_many :order_flavors
  has_many :flavors, through: :order_flavors

  validates :customer_name, presence: true
  validates :city, presence: true
  validates :state,
    presence: true,
    inclusion: { in: STATES.map { |state| state[1] } }
  validates :quantity,
    presence: true,
    numericality: { only_integer: true },
    inclusion: { in: QUANTITIES.map { |quantity| quantity[0] } }
  validates :ranch_dressing, inclusion: { in: [true, false] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/wing_orders_controller.rb
class WingOrdersController < ApplicationController
  def index
    @wing_orders = WingOrder.all
  end

  def new
    @wing_order = WingOrder.new
    @state_collection = WingOrder::STATES
    @quantity_collection = WingOrder::QUANTITIES
    @flavor_collection = Flavor.all
  end

  def create
    @wing_order = WingOrder.new(wing_order_params)
    if @wing_order.save
      flash[:notice] = "Wing order created!"
      redirect_to wing_orders_path
    else
      flash[:alert] = "Wing order not created"
      @state_collection = WingOrder::STATES
      @quantity_collection = WingOrder::QUANTITIES
      @flavor_collection = Flavor.all
      erb :new
    end
  end

  private

  def wing_order_params
    params.require(:wing_order).permit(
      :customer_name,
      :city,
      :state,
      :quantity,
      :dressing,
      flavor_ids: []
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">
      <div class="columns small-12">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/wing_orders/index.html.erb
<h1>Wing Orders</h1>

<div class=".wing_orders">
<%  @wing_orders.each do |wing_order| %>
  <div class=".wing_order">
    <h2><%= wing_order.customer_name %></h2>
    <span><%= "#{wing_order.city}, #{wing_order.state}" %></span>
    <span>Quantity: <%= wing_order.quantity %></span>
    <span>Include Ranch Dressing?: <%= wing_order.ranch_dressing %></span>
    <h3>Flavors To Include</h3>
    <% wing_order.flavors.each do |flavor| %>
      <span><%= flavor.name %></span>
    <% end %>
  </div>
  <hr />
<% end %>
</div>

<%= link_to "New Order", new_wing_order_path %>

app/views/wing_orders/new.html.erb
<h1>New Wing Order</h1>

<%= form_for(@wing_order) do |f| %>
    <div class="field">
      <%= f.label "Full Name" %>
      <%= f.text_field :customer_name %>
    </div>

    <div class="field">
      <%= f.label :city %>
      <%= f.text_field :city %>
    </div>

    <div class="field">
      <%= f.label :state %>
      <%= f.select :state, @state_collection%>
    </div>

    <div class="field">
      <%= f.label :quantity %>
      <% @quantity_collection.each do |num| %>
        <%= f.radio_button :quantity, num.first %> <%= num.last%></br>
      <% end %>
    </div>

    <div class="field">
      <%= check_box_tag(:ranch_dressing) %>
      <%= label_tag(:ranch_dressing, "Add Ranch Dressing") %> <br />
    </div>

    <div class="field">
      <%= f.label "Flavors" %>
      <!-- collection_check_boxes(object, method, collection, value_method, text_method) -->
      <%= collection_check_boxes(:wing_order, :flavor_ids, @flavor_collection, :id, :name) %>
    </div>


    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>